export const STATUSES_STORE = 'statuses'
export const STATUS_TIMELINES_STORE = 'status_timelines'
export const META_STORE = 'meta'
export const ACCOUNTS_STORE = 'accounts'
export const RELATIONSHIPS_STORE = 'relationships'
export const NOTIFICATIONS_STORE = 'notifications'
export const NOTIFICATION_TIMELINES_STORE = 'notification_timelines'